server.port=8081

# Give preference to local setting if configured
spring.cloud.config.allow-override=true
spring.cloud.config.override-none=true

eureka.client.serviceUrl.defaultZone=http://localhost:7090/eureka


spring.datasource.url= jdbc:postgresql://localhost:5432/pizza_db

spring.datasource.username=postgres

spring.datasource.password=raja



spring.jpa.hibernate.ddl-auto = none


spring.jpa.show-sql = true


spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect


