create table IF NOT EXISTS pizza(
    orderId integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1001) PRIMARY KEY,
    pizzaName varchar(20),
    quantity int,
    bill double precision,
    customerContactNumber varchar(10)
);

insert into pizza (pizzaName,quantity,bill,customerContactNumber) values
  ('Margherita',1,200,'1234567890'),
  ('Pepperoni',2,400,'9543214753'),
  ('Veggie Supreme',3,600,'5843919283'),
  ('Four Cheese',2,400,'3742828282');