name: Build and Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

permissions:
  contents: write # Required to push to the gh-pages branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          cd frontend
          npm install

      - name: Build Angular Application
        run: |
          cd frontend
          npx ng build --configuration production --base-href /Dummynos/
          # Create the 404.html fallback page
          cp dist/pizza-app/browser/index.html dist/pizza-app/browser/404.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: frontend/dist/pizza-app/browser
          branch: gh-pages
